### PR TITLE
Build system

### PR DESCRIPTION
**Pull request by mastertnt**
Create a build pipeline with nuke , the different stages are:
- restore : Restore all dependencies
- clean : Clean all binaries
- compile : Compile the solution in debug or release.
- pack : create a nuget package

The assembly has been ported to .NET 5.0

### CODE REVIEW

**Comment by mastertnt** [comment]
Do you need more information to merge the PR ?

**Comment by mastertnt** [comment]
No news ? @leif81

**Comment by leif81** [comment]
Is it possible to setup this new build system with Travis or GitHub Actions to show it working. Do you have interest in doing that?

**Comment by mastertnt** [comment]
Yes i can do it on my branch

**Comment by mastertnt** [comment]
I will restart with Github actions only you can destroy the pull request

**Comment by chausen** [comment]
Did anything ever come of this? The upgrade to .NET 5.0 so this could be used on Linux would be nice.

**Pull request closed without merging**
