### PR TITLE
Cleanup and Modernisation

### PR DESCRIPTION
**Pull request by las-nsc**
# Includes
- Upgrade to C#9
- Applied IDE and Roslynator suggestions to entire solution (except below)
- Fixed most warnings (except below)
- Used `<inheritdoc/>` where possible (added interfaces where necessary)
- Wrapped comments if over 110 chars wide
- Updated projects to SDK-style with common .props file.

## Excludes
IDE/compiler:
- Remove Suppression (not tried to use code analysis, so not sure if still needed)
- Missing XML documentation comments
- `RepairCompletePdu` `Padding` property hides inherited member
- Unnecessary parenthesis (Left in some for clarity)

Roslynator:
- Use ++ operator
- Optimise `StringBuilder.AppendLine`
- Declare enum member with 0 value when has FlagsAttribute
- Duplicate enum/Sort enums by value

### CODE REVIEW

**Comment by leif81** [comment]
Thank-you for this PR @las-nsc !

I will try to review within the next week or so.

Note I'm not a C# expert so if any of the other recent contributors are available to help with the review and also provide feedback I'd appreciate the help. @rodneyp290 @cdettmering-unity

**Comment by cdettmering-unity** [comment]
> Thank-you for this PR @las-nsc !
> 
> I will try to review within the next week or so.
> 
> Note I'm not a C# expert so if any of the other recent contributors are available to help with the review and also provide feedback I'd appreciate the help. @rodneyp290 @cdettmering-unity


@las-nsc is this PR a result of just using the visual studio upgrade to newer version of C# feature? Or is some of this hand written? I generally like the approach of using var (when you can) and adding in things like readonly properties. I have to look a lot more at this PR because it's huge, just trying to get an idea if all of these changes were automated in some way.

**Comment by las-nsc** [comment]
@cdettmering-unity most of the changes were made using analyser suggestions from VS2019 and Roslynator, or with regular expressions. Hopefully reviewing the changes by commit should make it easier to tell how closely the changes need to be checked?

**Comment by leif81** [comment]
@las-nsc this PR is still marked as WIP. When you're ready for final review can you click the readu-for-review button. And is there anything fixed or added in the PR that wasn't related to fixing warnings or IDE suggestions? If so it just makes it easier to review because it is a large PR to review otherwise. Thanks!

@cdettmering-unity appreciate your comments and second set of eyes and thoughts.

**Comment by las-nsc** [comment]
@leif81 Yes, I did so because I wasn't sure if there would be any extra steps you might want me or someone else to take before seriously reviewing it. I'm fairly confident I won't have broken anything due to the nature of my changes, but I was thinking that someone with a codebase with higher code utilisation might want to verify it still behaves as before, since there aren't unit tests.

**Comment by leif81** [comment]
@las-nsc Yes ideally we'd have a set of unit tests to confirm a large refactor like this doesn't cause blow up anything. 

Are you using this change in your own project and if so have you observed any issues with this ? 

I don't have any other concerns and I've not heard any concerns raised from any others at this time. So once you are able to confirm the change works for you then at that point I'm good to proceed and merge.

**Comment by leif81** [comment]
A lot of effort went into this PR I can tell. I'd have liked to see unit tests for a change this large, but I also don't like seeing large effort bit rot. Any have strong concerns about merging this as is? I'll wait for comments for one week and then merge if no objections. Thanks.

**Pull request merged**
